# Generated by Django 3.2 on 2024-05-30 02:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_module_basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='areas', to=settings.AUTH_USER_MODEL),
        ),
    ]
