# Generated by Django 3.2 on 2024-06-01 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_module_basic', '0005_alter_modeltest_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_module_basic.category'),
        ),
    ]
