# Generated by Django 3.2 on 2024-06-01 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_module_basic', '0006_alter_modeltest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltest',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models_created', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeltest',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='django_module_basic.category'),
            preserve_default=False,
        ),
    ]
